apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: carlibraryviewer
  name: carlibraryviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carlibraryviewer
  template:
    metadata:
      labels:
        app: carlibraryviewer
    spec:
      containers:
      - name: carlibraryviewer
        image: tomsearcher/carlibraryviewer
        env:
        - name: REACT_APP_API_URL
          value: "https://api.toms-lab.net/gateway/carlibraryapi"
        - name: REACT_APP_OAUTH_URL
          value: "https://authorize.toms-lab.net/carlibraryauth"
        - name: REACT_APP_OAUTH_CLIENT_ID
          value: "dc83392c-9486-4ad6-8339-2c94866ad6b1"
        - name: REACT_APP_OAUTH_CLIENT_SECRET
          value: "ZGM4MzM5MmMtOTQ4Ni00YWQ2LTgzMzktMmM5NDg2NmFkNmIxOmtPTlZoZzJYWVAwUHQ2bkROSUZTMkZzYWMzQW9hLUs0U2NFc2kyRVpNdW8="
        ports:
          - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: carlibraryviewer
  labels:
    app: carlibraryviewer
spec:
  ports:
  - port: 3000
    name: carlibraryviewer
  clusterIP: None
  selector:
    app: carlibraryviewer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/app-root: /
    kubernetes.io/ingress.class: nginx
    kubernetes.io/rewrite-target: /
  generation: 1
  name: carlibraryviewer
spec:
  rules:
  - host: carlibraryviewer.toms-lab.net
    http:
      paths:
      - backend:
          serviceName: carlibraryviewer
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - carlibraryviewer.toms-lab.net
    #secretName: api-custom-cert
