apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data-elasticsearch
  name: data-elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
  selector:
    app: elasticsearch
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: elasticsearch
        - name: discovery.type
          value: single-node
        - name: http.host
          value: 0.0.0.0
        - name: transport.host
          value: 0.0.0.0
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.security.enabled
          value: "false"
        - name: TAKE_FILE_OWNERSHIP
          value: 'true'
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        imagePullPolicy: Always
        name: gio-apim-elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data-elasticsearch
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data-elasticsearch
        persistentVolumeClaim:
          claimName: data-elasticsearch
status: {}
